language: go

go:
  - 1.3
  - 1.4
  - 1.5
  - 1.6
  - 1.7

os:
  - linux
  - osx

script:
  - go get ./dobuild
  - go install ./dobuild
  - go get github.com/mattn/goveralls
  - go test ./libdobuild -v -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls --coverprofile=coverage.out -service=travis-ci
